src/Entity/Sighting.php
<?php

namespace App\Entity;

use App\Entity\Taxon\Species;
use App\Repository\SightingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use DateTime;

#[ORM\Entity(repositoryClass: SightingRepository::class)]
#[ORM\Table(name:'taxon_species')]
class Sighting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'Sightings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User;

    #[ORM\ManyToOne(targetEntity: Species::class, inversedBy: 'Sightings')]
    #[ORM\JoinColumn(nullable: false)]
	#[ORM\JoinTable(name:'sighting_species')]
    private ?Species $Species;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $Location;

    #[ORM\Column(type: 'datetime')]
    private ?DateTime $DateTime;

    #[ORM\Column(type: 'string', length: 512, nullable: true)]
    private ?string $Comment;

    #[ORM\ManyToMany(targetEntity: Card::class, mappedBy: 'Sightings')]
    private Collection $Cards;

    public function __construct()
    {
        $this->Cards = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getSpecies(): ?Species
    {
        return $this->Species;
    }

    public function setSpecies(?Species $Species): self
    {
        $this->Species = $Species;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(?string $Location): self
    {
        $this->Location = $Location;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->DateTime;
    }

    public function setDateTime(\DateTimeInterface $DateTime): self
    {
        $this->DateTime = $DateTime;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->Comment;
    }

    public function setComment(?string $Comment): self
    {
        $this->Comment = $Comment;

        return $this;
    }

    /**
     * @return Collection<int, Card>
     */
    public function getCards(): Collection
    {
        return $this->Cards;
    }

    public function addCard(Card $card): self
    {
        if (!$this->Cards->contains($card)) {
            $this->Cards->add($card);
            $card->addSighting($this);
        }

        return $this;
    }

    public function removeCard(Card $card): self
    {
        if ($this->Cards->removeElement($card)) {
            $card->removeSighting($this);
        }

        return $this;
    }
}

src/Entity/Taxon/Species.php
<?php

namespace App\Entity\Taxon;

use App\Entity\Card;
use App\Entity\Sighting;
use App\Repository\Taxon\SpeciesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SpeciesRepository::class)]
class Species {
	#[ORM\Id]
	#[ORM\GeneratedValue]
	#[ORM\Column(type: 'integer')]
	private ?int $id;
	#[ORM\Column(type: 'integer')]
	#[Assert\NotNull]
	private ?int $TaxonomyId;
	#[ORM\Column(type: 'string', length: 255)]
	#[Assert\NotNull]
	private ?string $ScientificName;
	#[ORM\Column(type: 'string', length: 255, nullable: true)]
	private ?string $VernacularName;
	#[ORM\ManyToOne(targetEntity: Genus::class, inversedBy: 'species')]
	#[ORM\JoinColumn(nullable: true)]
	#[Assert\NotNull]
	private ?Genus $Genus;
	private ?Family $Family;
	#[ORM\OneToMany(mappedBy: 'Species', targetEntity: Sighting::class, orphanRemoval: true)]
	private Collection $Sightings;
	#[ORM\ManyToMany(targetEntity: Card::class, mappedBy: 'Species')]
	#[ORM\JoinTable(name: 'card_species')]
	private Collection $Cards;
	#[ORM\Column(length: 255, nullable: true)]
	private ?string $SwedishProminence = null;

	public function __construct(){
		$this->Sightings = new ArrayCollection();
		$this->Cards = new ArrayCollection();
	}

	function __toString(){
		return "{$this->VernacularName}  ({$this->ScientificName})";
	}

	public function getId(): ?int{
		return $this->id;
	}

	public function getTaxonomyId(): ?int{
		return $this->TaxonomyId;
	}

	public function setTaxonomyId(int $TaxonomyId): self{
		$this->TaxonomyId = $TaxonomyId;

		return $this;
	}

	public function getScientificName(): ?string{
		return $this->ScientificName;
	}

	public function setScientificName(string $ScientificName): self{
		$this->ScientificName = $ScientificName;

		return $this;
	}

	public function getVernacularName(): ?string{
		return $this->VernacularName;
	}

	public function setVernacularName(?string $VernacularName): self{
		$this->VernacularName = $VernacularName;

		return $this;
	}

	public function getGenus(): ?Genus{
		return $this->Genus;
	}

	public function setGenus(?Genus $Genus): self{
		$this->Genus = $Genus;

		return $this;
	}

	/**
	 * @return Collection<int, Sighting>
	 */
	public function getSightings(): Collection{
		return $this->Sightings;
	}

	public function addSighting(Sighting $sighting): self{
		if (!$this->Sightings->contains($sighting)) {
			$this->Sightings[] = $sighting;
			$sighting->setSpecies($this);
		}

		return $this;
	}

	public function removeSighting(Sighting $sighting): self{
		if ($this->Sightings->removeElement($sighting)) {
			// set the owning side to null (unless already changed)
			if ($sighting->getSpecies() === $this) {
				$sighting->setSpecies(null);
			}
		}

		return $this;
	}

	function getFullName(): string{
		return "{$this->VernacularName} ({$this->ScientificName})";
	}

	function getFamily(): ?Family{
		return $this->Genus->getFamily();
	}

	/**
	 * @return Collection<int, Card>
	 */
	public function getCards(): Collection{
		return $this->Cards;
	}

	public function addCard(Card $card): self{
		if (!$this->Cards->contains($card)) {
			$this->Cards->add($card);
			$card->addSpecies($this);
		}

		return $this;
	}

	public function removeCard(Card $card): self{
		if ($this->Cards->removeElement($card)) {
			$card->removeSpecies($this);
		}

		return $this;
	}

	public function getSwedishProminence(): ?string{
		return $this->SwedishProminence;
	}

	public function setSwedishProminence(string $SwedishProminence): self{
		$this->SwedishProminence = $SwedishProminence;

		return $this;
	}
}

src/Form/SightingType.php
<?php

namespace App\Form;

use App\Entity\Sighting;
use App\Entity\Taxon\Species;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SightingType extends AbstractType {
	public function buildForm(FormBuilderInterface $builder, array $options): void{
		$builder
			->add('Location', TextType::class, [
				'label' => 'Plats'
			])
			->add('DateTime', DateTimeType::class, [
				'widget' => 'single_text',
				'label' => 'Tidpunkt'
			])
			->add('Comment', TextareaType::class, [
				'label' => 'Kommentar'
			])
			->add('Species', EntityType::class, [
				'autocomplete' => true,
				'class' => Species::class,
				'label' => 'Art'
			]);
	}

	public function configureOptions(OptionsResolver $resolver): void{
		$resolver->setDefaults([
								   'data_class' => Sighting::class,
							   ]);
	}
}

src/Controller/SightingController.php
<?php

namespace App\Controller;

use App\Entity\Sighting;
use App\Entity\Taxon\Species;
use App\Form\SightingType;
use App\Repository\SightingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/sighting')]
class SightingController extends AbstractController {
	#[Route('/list/{p}', name: 'app_sighting_index', methods: ['GET'])]
	public function index(SightingRepository $sightingRepository, int $p = 0): Response{
		$sightings = $sightingRepository->createQueryBuilder('qb')->setMaxResults(50);
		if ($p > 0) {
			$sightings->setFirstResult($p * 50);
		}
		return $this->render('sighting/index.html.twig', [
			'sightings' => $sightings->getQuery()->getResult(),
		]);
	}

	#[Route('/new/{species}', name: 'app_sighting_new', methods: ['GET', 'POST'])]
	#[IsGranted('ROLE_USER')]
	public function new(Request $request, EntityManagerInterface $entityManager, Species $species = null): Response{
		$sighting = new Sighting();
		if ($species)
			$sighting->setSpecies($species);

		$form = $this->createForm(SightingType::class, $sighting);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$sighting->setUser($this->getUser());
			$entityManager->persist($sighting);
			$entityManager->flush();

			return $this->redirectToRoute('app_sighting_index', [], Response::HTTP_SEE_OTHER);
		}

		return $this->render('sighting/new.html.twig', [
			'sighting' => $sighting,
			'form' => $form,
		]);
	}

	#[Route('/{id}', name: 'app_sighting_show', methods: ['GET'])]
	public function show(Sighting $sighting): Response{
		$species = $this->renderView('Partials/artfakta.html.twig', ['taxon' => $sighting->getSpecies()->getTaxonomyId()]);
		return $this->render('sighting/show.html.twig', [
			'sighting' => $sighting,
			'species' => $species
		]);
	}

	#[Route('/{id}/edit', name: 'app_sighting_edit', methods: ['GET', 'POST'])]
	public function edit(Request $request, Sighting $sighting, EntityManagerInterface $entityManager): Response{
		if ($sighting->getUser() !== $this->getUser()) throw  new UnauthorizedHttpException();

		$form = $this->createForm(SightingType::class, $sighting);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$entityManager->flush();

			return $this->redirectToRoute('app_sighting_index', [], Response::HTTP_SEE_OTHER);
		}

		return $this->render('sighting/edit.html.twig', [
			'sighting' => $sighting,
			'form' => $form,
		]);
	}

	#[Route('/{id}', name: 'app_sighting_delete', methods: ['POST'])]
	public function delete(Request $request, Sighting $sighting, EntityManagerInterface $entityManager): Response{
		if ($sighting->getUser() !== $this->getUser()) throw  new UnauthorizedHttpException();

		if ($this->isCsrfTokenValid('delete' . $sighting->getId(), $request->request->get('_token'))) {
			$entityManager->remove($sighting);
			$entityManager->flush();
		}

		return $this->redirectToRoute('app_sighting_index', [], Response::HTTP_SEE_OTHER);
	}
}

templates/sighting/_delete_form.html.twig
<form method="post" action="{{ path('app_sighting_delete', {'id': sighting.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sighting.id) }}">
    <button class="btn">Radera</button>
</form>

templates/sighting/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Spara') }}</button>
{{ form_end(form) }}

templates/sighting/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Redigera glutt{% endblock %}

{% block body %}
	<h1>Redigera</h1>

	{{ include('sighting/_form.html.twig', {'button_label': 'Uppdatera'}) }}
	{{ include('sighting/_delete_form.html.twig') }}
{% endblock %}

templates/sighting/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Spanlista{% endblock %}

{% block body %}
	<h1>Skådningar</h1>

	<ul>
		{% for sighting in sightings %}
			<li class="">
				<div>
					<div class="sighting">
						<span>{{ sighting.species.fullName }}</span>
						<span>{{ sighting.location }}</span>
						<span>{{ sighting.dateTime|date('Y-m-d') }}</span>
						<span>{{ sighting.comment }}</span>
					</div>

					<div class="links">
						<a href="{{ path('app_sighting_show', {'id': sighting.id}) }}">Visa</a>
						{% if sighting.user == app.user %}

							<a href="{{ path('app_sighting_edit', {'id': sighting.id}) }}">Registera</a>
						{% endif %}
					</div>
				</div>
			</li>
		{% else %}
			<h2>no records found</h2>
		{% endfor %}
	</ul>
	<a href="{{ path('app_sighting_new') }}">Registrera nytt</a>
{% endblock %}

templates/sighting/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Sighting{% endblock %}

{% block body %}
	<h1>Registrera glutt</h1>

	{{ include('sighting/_form.html.twig') }}

	<a href="{{ path('app_sighting_index') }}" class="button">Visa tidigare</a>
{% endblock %}

templates/sighting/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sighting{% endblock %}

{% block body %}
	<h1>Glutt</h1>
	<br>
	<a href="{{ path('app_sighting_index', {'p':0}) }}" class="arrow">Till listan</a>
	{% if sighting.user == app.user %}
		<a href="{{ path('app_sighting_edit', {'id': sighting.id}) }}" class="button small">Redigera</a>
		<a href="{{ path('app_sighting_delete', {'id': sighting.id}) }}" class="button small">Radera</a>
	{% endif %}

	<hr>

	<h3><small>Art: </small>{{ sighting.species }}</h3>
	<h3><small>Tid: </small>{{ sighting.dateTime|date('Y-m-d H:i') }}</h3>
	<h3><small>Plats: </small>{{ sighting.location }}</h3>
	<h3><small>Kommentar: </small>{{ sighting.comment }}</h3>
	<h3><small>Reggat av: </small>{{ sighting.user }}</h3>

	<section class="species-data col-2">
		{{ species|raw }}
	</section>

{% endblock %}